version: '3.9'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      MARIADB_ROOT_PASSWORD: VlL1d&fm%09q
      MARIADB_DATABASE: pfse_db
      MARIADB_USER: pfse_db_admin
      MARIADB_PASSWORD: 4t37cORtee@C
  wordpress:
    image: docker.io/bitnami/wordpress-nginx:6
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - ./nginx/wordpress-nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
    depends_on:
      - mariadb
    environment:
#      WORDPRESS_EMAIL: 
#      WORDPRESS_FIRST_NAME: 
#      WORDPRESS_LAST_NAME:
#      WORDPRESS_BLOG_NAME: 
      WORDPRESS_DATABASE_HOST: mariadb
      WORDPRESS_DATABASE_USER: pfse_db_admin
      WORDPRESS_DATABASE_PASSWORD: 4t37cORtee@C
      WORDPRESS_DATABASE_NAME: pfse_db
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_USERNAME: pfse_admin_user
      WORDPRESS_PASSWORD: 9vuNOq!8e18G
      PHP_UPLOAD_MAX_FILESIZE: 1000M
      PHP_POST_MAX_SIZE: 1000M
      PHP_MEMORY_LIMIT: 1000M
      PHP_MAX_EXECUTION_TIME: 300000
      PHP_MAX_INPUT_TIME: 300000
    restart: always
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local